### ISSUE TITLE
file descriptors

### ISSUE THREAD

**Issue by hannesm** [hannesm/tlstunnel#14]
not sure whether it is right to close `s`, instead of `t`. Now, no `CLOSE_NOTIFY` is sent to the other side (but also, no fd is leaked!).

https://github.com/mirleft/ocaml-tls/blob/master/lwt/tls_lwt.ml#L61-L62 seems to leak an fd if the write fails (can a lwt write fail?)...

**Comment by avsm** [comment]
It would be nice to have a little Lwt "leak detector" that we could log every so often in order to see how many live FDs there are. Would be useful in Cohttp stress tests too...
-a
