### ISSUE TITLE
Tlstunnel not found

### ISSUE THREAD

**Issue by Fen0l** [hannesm/tlstunnel#21]
Hi, I have installed tlstunnel on mac os el capitan but the command is not found

[ John  ~/.opam ] opam install tlstunnel
[NOTE] Package tlstunnel is already installed (current version is 0.1.1).
[ John  ~/.opam ] tlstunnel
-bash: tlstunnel: command not found
[ John  ~/.opam ] 

Where can I find the binary ? thanks

**Comment by hannesm** [comment]
it should be in `.opam/$switch/bin` (if you run `eval `opam config env``, your`$PATH` will be extended with the current switch)

**Comment by hannesm** [comment]
@Fen0l any news on this? were you able to find the binary? please reopen if this is still relevant.
