### ISSUE TITLE
access logging?

### ISSUE THREAD

**Issue by avsm** [hannesm/tlstunnel#3]
Simple access logging to a file for production would be handy

**Comment by hannesm** [comment]
what kind of access? I'd like to avoid a HTTP dependency in `tlstunnel`...

**Comment by avsm** [comment]
oh i just mean open a file for append and write a log entry on every connection accept.  Something that gives us useful info (which ciphers got negotiated) would be nice so we can analyse it.

**Comment by avsm** [comment]
stud has

```
LOGGING:
  -q  --quiet                Be quiet; emit only error messages
  -s  --syslog               Send log message to syslog in addition to stderr/stdout
  --syslog-facility=FACILITY Syslog facility to use (Default: "daemon")
```

**Comment by hannesm** [comment]
this sounds like my `-l` command line argument... (by default, the output is to stdout) -- having a `-q` would improve the situation if caring about privacy

**Comment by avsm** [comment]
ack, will try that later.

**Comment by hannesm** [comment]
what is logged:
- timestamp and source of (client connection)[https://github.com/hannesm/tlstunnel/blob/master/src/tlstunnel.ml#L71]
- timestamp of [forwarded connection](https://github.com/hannesm/tlstunnel/blob/master/src/tlstunnel.ml#L84) to service
- timestamp and bytes read/written on [teardown](https://github.com/hannesm/tlstunnel/blob/master/src/tlstunnel.ml#L94)
