### ISSUE TITLE
HAProxy PROXY command

### ISSUE THREAD

**Issue by avsm** [hannesm/tlstunnel#6]
The HaProxy support involves a small prefix with the original IP.  See stud README for more:

https://github.com/bumptech/stud

**Comment by hannesm** [comment]
the HAProxy protocol is specified [here](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt)

**Comment by cfcs** [comment]
PR here. https://github.com/hannesm/tlstunnel/pull/22

**Comment by cfcs** [comment]
List of software supporting HA PROXY v1: http://blog.haproxy.com/haproxy/proxy-protocol/

(I guess tlstunnel now has a place on that list, too?)

**Comment by hannesm** [comment]
I tested this locally works nicely.  should I do a new release of tlstunnel, now with proxy protocol support?
